image: node:lts-bullseye

# services:
#   - name: arangodb/arangodb:3.7.12
#     alias: db

build:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - npm run lint
    # TODO Run prettier --check to enforce merge requests are formatted correctly
  # TODO reuse artifacts in workspace specific ci tasks like tests
  # artifacts:
  #   paths:
  #     - node_modules
  #     - schema/dist
  #     - database/dist
  #     - app/.next

# TODO test running `npm run seed seeds/test`
