image: node:lts

# services:
#   - name: arangodb/arangodb:3.7.12
#     alias: db


app:
  cache:
    key:
      files:
        - app/package-lock.json
    paths:
      - .npm/

  before_script:
    - cd app
  script:
    - npm install --cache .npm --prefer-offline
    - npm run build
    - npm run lint
