image: node:lts-bullseye

# services:
#   - name: arangodb/arangodb:3.7.12
#     alias: db


app:
  cache:
    key:
      files:
        - app/package-lock.json
    paths:
      - app/.npm/

  before_script:
    # OS deps to convert mermaid graph in *.md files to SVG
    # For list of deps see https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
    - apt-get update -qq && apt-get install -y -qq ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
    - cd app
  script:
    - npm install --cache .npm --prefer-offline
    - npm run build
    - npm run lint

# TODO test running `npm run seed seeds/test`
